# Generated by Django 5.0 on 2023-12-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file_path', models.CharField(max_length=200)),
                ('target_file_path', models.CharField(max_length=200)),
                ('file_type', models.CharField(choices=[('source', 'Source'), ('target', 'Target')], max_length=10)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
